//
//  Constants.h
//  whatsgoinon
//
//  Created by adeiji on 8/12/14.
//  Copyright (c) 2014 adeiji. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_EVENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_ACTIVE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_TITLE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_ADDRESS;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_DESCRIPTION;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_START_TIME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_END_TIME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_COST;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_CATEGORY;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_POST_RANGE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_USER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_LOCATION;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_IMAGES;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_OBJECT_ID;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_COMMENTS;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_RATING;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_QUICK_DESCRIPTION;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_NUMBER_GOING;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_USERNAME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_VIEW_COUNT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_THUMBS_UP_COUNT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_STATUS;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_STATUS_POSTED;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_WEBSITE;

FOUNDATION_EXPORT NSString *const TRENDING_ORDER;
FOUNDATION_EXPORT NSString *const LOCATION_LATITUDE;
FOUNDATION_EXPORT NSString *const LOCATION_LONGITUDE;

// PFObject - Report
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_REPORT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_WHATS_WRONG;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_OTHER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_EVENT_ID;
FOUNDATION_EXPORT NSString *const REPORT_VULGAR_OR_ABUSIVE_LANGUAGE;
FOUNDATION_EXPORT NSString *const REPORT_CRUDE_CONTENT;
FOUNDATION_EXPORT NSString *const REPORT_NOT_REAL_POST;
FOUNDATION_EXPORT NSString *const REPORT_POST_NOT_APPROPRIATE;

//PFObject - Miscategorized
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_MISCATEGORIZED_EVENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_MISCATEGORIZED_EVENT_CATEGORY;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_MISCATEGORIZED_EVENT_ID;


// Parse - Comment
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_COMMENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_COMMENT_COMMENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_COMMENT_USER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_COMMENT_THUMBS_UP;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_COMMENT_EVENT_ID;
FOUNDATION_EXPORT NSString *const PROMPT_COMMENT_FOR_EVENT;
FOUNDATION_EXPORT NSString *const SHOW_COMMENT_VIEW;
FOUNDATION_EXPORT NSString *const SEE_IF_CAN_COMMENT;

// Parse - User
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_USER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_USERNAME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_EMAIL;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_PASSWORD;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_VISIBLE_PASSWORD;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_EMAIL_VERIFIED;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_PROFILE_PICTURE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_EVENTS_GOING;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_EVENTS_MAYBE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_POST_COUNT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_RANK;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_CREATED_AT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_STATE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_USER_CITY;

// Parse - Analytics
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_ANALYTICS;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_TIME;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_EVENT_NAME;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_DISTANCE_TO_EVENT;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_DID_SHOW_LOCAL_NOTIFICATION;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_DISTANCE_TRAVELED;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_TIME_LAPSED;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_LATITUDE;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_LONGITUDE;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_START_TIME;
FOUNDATION_EXPORT NSString *const PARSE_ANALYTICS_END_TIME;

// Places Google Maps API
FOUNDATION_EXPORT NSString *const PLACES_API_DATA_RESULT_TYPE_CITIES;
FOUNDATION_EXPORT NSString *const PLACES_API_DATA_RESULT_TYPE_GEOCODE;
FOUNDATION_EXPORT NSString *const PLACES_API_NO_RESULTS;


// Orb Button View
FOUNDATION_EXPORT NSString *const ORB_BUTTON_VIEW;;
FOUNDATION_EXPORT CGFloat const BUTTON_CORNER_RADIUS;

// Notifications
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_ALL_EVENTS_LOADED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_ALL_NO_EVENTS_POSTED_BY_USER;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_USERS_EVENTS_LOADED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_PAST_EPIC_EVENTS_LOADED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_CITY_CHANGED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_NO_DATA;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_NONE_IN_CATEGORY;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_ALL_COMMENTS_LOADED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_POST_FROM_USER_RETRIEVED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_USER_RANK_RETRIEVED;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_CATEGORY;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_USER_RETRIEVED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_NO_SAVED_EVENTS;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_SAVED_EVENTS_LOADED;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_LOAD_USER_EVENTS;
FOUNDATION_EXPORT NSString *const NOTIFICATION_LATER_EVENTS_ADDED;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_USER_EVENTS_COUNT;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_RANK_OBJECT_INFO;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_USER_PROCESS;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_USER_PROCESS_STILL_LOADING;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_IS_CITY_CHANGE;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_USER_PROCESS_FINISHED_LOADING;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_ORB_CLICKED;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_USER_PROCESS_NEW;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_USER_INFO_IS_EPIC_EVENTS;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_EVENT_USER_AT;
FOUNDATION_EXPORT NSString *const kNOTIFICATION_CENTER_LOCAL_NOTIFICATION_FUTURE;
FOUNDATION_EXPORT NSString *const NOTIFICATION_CENTER_USER_INFO_POSOTED_BY_ME;

// View Controllers
FOUNDATION_EXPORT NSString *const PROMPT_LOGIN_VIEW_CONTROLLER;
FOUNDATION_EXPORT NSString *const LOGIN_ADD_PROFILE_IMAGE_VIEW_CONTROLLER;

// NSUserDefaults
FOUNDATION_EXPORT NSString *const NSUSER_DEFAULTS_PROFILE_PICTURE;
FOUNDATION_EXPORT NSString *const EPIC_EVENTS_SCREEN_PROMPTED;

// User Ranks
FOUNDATION_EXPORT NSString *const USER_RANK_AMBASSADOR;
FOUNDATION_EXPORT NSString *const USER_RANK_ADMIN;
FOUNDATION_EXPORT NSString *const USER_RANK_STANDARD;

// Categories
FOUNDATION_EXPORT NSString *const CATEGORY_TRENDING;

// Parse Image Dimensions Constants
FOUNDATION_EXPORT NSString *const IMAGE_DIMENSION_WIDTH;
FOUNDATION_EXPORT NSString *const IMAGE_DIMENSION_HEIGHT;

// Parse Local Datastore
FOUNDATION_EXPORT NSString *const kGOING_POST_LOCAL_DATASTORE;
FOUNDATION_EXPORT NSString *const kAnalytics;
FOUNDATION_EXPORT NSString *const kAnalyticsArray;
FOUNDATION_EXPORT int const DISTANCE_TO_EVENT_FOR_COMMENTING;