//
//  Constants.h
//  whatsgoinon
//
//  Created by adeiji on 8/12/14.
//  Copyright (c) 2014 adeiji. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_EVENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_ACTIVE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_TITLE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_ADDRESS;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_DESCRIPTION;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_START_TIME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_END_TIME;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_COST;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_CATEGORY;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_POST_RANGE;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_USER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_LOCATION;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_IMAGES;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_EVENT_OBJECT_ID;

// PFObject - Report
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_REPORT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_WHATS_WRONG;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_OTHER;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_REPORT_EVENT_ID;
FOUNDATION_EXPORT NSString *const REPORT_VULGAR_OR_ABUSIVE_LANGUAGE;
FOUNDATION_EXPORT NSString *const REPORT_CRUDE_CONTENT;
FOUNDATION_EXPORT NSString *const REPORT_NOT_REAL_POST;
FOUNDATION_EXPORT NSString *const REPORT_POST_NOT_APPROPRIATE;

//PFObject - Miscategorized
FOUNDATION_EXPORT NSString *const PARSE_CLASS_NAME_MISCATEGORIZED_EVENT;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_MISCATEGORIZED_EVENT_CATEGORY;
FOUNDATION_EXPORT NSString *const PARSE_CLASS_MISCATEGORIZED_EVENT_ID;













