//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 11/17/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "HPStyleKit.h"


@implementation HPStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawAmbassadorFlagInRect: (CGRect)frame;
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];


    //// Subframes
    CGRect group2 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.07152 - 0.3) + 0.8, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.04803) + 0.5, floor(CGRectGetWidth(frame) * 0.95269 - 0.36) - floor(CGRectGetWidth(frame) * 0.07152 - 0.3) + 0.06, floor(CGRectGetHeight(frame) * 0.94685 - 0.3) - floor(CGRectGetHeight(frame) * 0.04803) + 0.3);


    //// Group 2
    {
        //// Group
        {
            //// Bezier 2 Drawing
            UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.99508 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38586 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.72537 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.40232 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.90327 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.39573 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.81719 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.40561 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.50731 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38586 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.65077 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.39902 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.58191 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.39573 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.08265 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38586 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.36958 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.36281 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.21464 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.35294 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.08839 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.07642 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.06544 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.28381 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.09987 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.18176 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.08265 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.06325 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.08839 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.07313 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.08265 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.06325 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.44992 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.05008 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.20316 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.04021 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.32367 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.04350 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.75406 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.08300 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.55321 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.05996 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.65077 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.07642 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.99508 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.06325 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.83440 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.08629 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.92048 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.08300 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.98934 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.37269 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 1.01230 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.16530 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.97787 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.26735 * CGRectGetHeight(group2))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.99508 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38586 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.98934 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.37598 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.99508 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38256 * CGRectGetHeight(group2))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.99508 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.38586 * CGRectGetHeight(group2))];
            [bezier2Path closePath];
            [UIColor.whiteColor setFill];
            [bezier2Path fill];
            [color0 setStroke];
            bezier2Path.lineWidth = 1.32;
            [bezier2Path stroke];
        }


        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.10289 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.02923 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.98318 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.01286 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.99260 * CGRectGetHeight(group2))];
        [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.01682 * CGRectGetHeight(group2))];
        [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.02923 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00740 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.01286 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.10289 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.13212 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.01682 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.11926 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.13212 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00740 * CGRectGetHeight(group2))];
        [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.13212 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.98318 * CGRectGetHeight(group2))];
        [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.10289 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2)) controlPoint1: CGPointMake(CGRectGetMinX(group2) + 0.13212 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.99226 * CGRectGetHeight(group2)) controlPoint2: CGPointMake(CGRectGetMinX(group2) + 0.11867 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier4Path closePath];
        bezier4Path.miterLimit = 4;

        [color0 setFill];
        [bezier4Path fill];
    }
}

+ (void)drawHappsnaplogoWithRectangle: (CGRect)rectangle
{
    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.5];
    UIColor* color4 = [UIColor colorWithRed: 0.25 green: 0.25 blue: 0.25 alpha: 0.35];
    UIColor* color2 = [UIColor colorWithRed: 0.092 green: 0.515 blue: 0.896 alpha: 1];
    UIColor* color1 = [UIColor colorWithRed: 0.219 green: 0.699 blue: 0.312 alpha: 1];
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Variable Declarations
    CGFloat textSize = rectangle.size.width / 6.21;
    
    //// Frames
    CGRect mainFrame = CGRectMake(3, -1, rectangle.size.width, rectangle.size.height);
    
    //// Subframes
    CGRect group4 = CGRectMake(CGRectGetMinX(mainFrame), CGRectGetMinY(mainFrame) + 46, CGRectGetWidth(mainFrame) + 43.3, CGRectGetHeight(mainFrame) - 46);
    
    
    //// Group 4
    {
        //// Rectangle 2 Drawing
        
        
        //// Group
        {
            //// Bezier 2 Drawing
            UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.39367 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.34357 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.29777 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47808 * CGRectGetHeight(group4))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.44412 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47808 * CGRectGetHeight(group4))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.39367 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.42525 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45788 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.40234 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.42150 * CGRectGetHeight(group4))];
            [bezier2Path closePath];
            bezier2Path.miterLimit = 4;
            
            [color1 setFill];
            [bezier2Path fill];
            
            
            //// Group 2
            {
                //// Bezier 4 Drawing
                UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
                [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.45837 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25804 * CGRectGetHeight(group4))];
                [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.43012 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28962 * CGRectGetHeight(group4))];
                [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.43493 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.29524 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.43012 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28962 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.42912 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.29692 * CGRectGetHeight(group4))];
                [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46854 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25952 * CGRectGetHeight(group4))];
                [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46618 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25400 * CGRectGetHeight(group4))];
                [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.45837 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25804 * CGRectGetHeight(group4))];
                [bezier4Path closePath];
                bezier4Path.miterLimit = 4;
                
                [color2 setFill];
                [bezier4Path fill];
                
                
                //// Bezier 6 Drawing
                UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
                [bezier6Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.52149 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.30146 * CGRectGetHeight(group4))];
                [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.47735 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25400 * CGRectGetHeight(group4))];
                [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.47317 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26189 * CGRectGetHeight(group4))];
                [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.51504 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.30738 * CGRectGetHeight(group4))];
                [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.52149 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.30146 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.51513 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.30738 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.52248 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.30817 * CGRectGetHeight(group4))];
                [bezier6Path closePath];
                bezier6Path.miterLimit = 4;
                
                [color2 setFill];
                [bezier6Path fill];
            }
            
            
            //// Bezier 8 Drawing
            UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
            [bezier8Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46854 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46836 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.46845 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.46845 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4))];
            [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.45405 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.18415 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.44967 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.18590 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.45092 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.18229 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.44967 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.18590 * CGRectGetHeight(group4))];
            [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46371 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24648 * CGRectGetHeight(group4))];
            [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46318 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24687 * CGRectGetHeight(group4))];
            [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46318 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24687 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.45852 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25604 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.46040 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24883 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.45852 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25224 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46854 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26697 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.45852 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26209 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.46300 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26697 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.47856 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25604 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.47409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26697 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.47856 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.26209 * CGRectGetHeight(group4))];
            [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46854 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.47856 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25000 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.47409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24512 * CGRectGetHeight(group4))];
            [bezier8Path closePath];
            bezier8Path.miterLimit = 4;
            
            [color1 setFill];
            [bezier8Path fill];
            
            
            //// Bezier 10 Drawing
            UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
            [bezier10Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.51050 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51768 * CGRectGetHeight(group4))];
            [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46801 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52734 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.51050 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52305 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.49145 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52734 * CGRectGetHeight(group4))];
            [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.42551 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51768 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.44457 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52734 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.42551 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52305 * CGRectGetHeight(group4))];
            [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46801 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50803 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.42551 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51232 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.44457 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50803 * CGRectGetHeight(group4))];
            [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.51050 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51768 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.49153 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50803 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.51050 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51242 * CGRectGetHeight(group4))];
            [bezier10Path closePath];
            bezier10Path.miterLimit = 4;
            
            [color3 setFill];
            [bezier10Path fill];
            
            
            //// Group 3
            {
                //// Bezier 12 Drawing
                UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
                [bezier12Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.59110 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.59631 * CGRectGetHeight(group4))];
                [bezier12Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.70570 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.59631 * CGRectGetHeight(group4))];
                [bezier12Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64925 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50768 * CGRectGetHeight(group4))];
                [bezier12Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.56131 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50768 * CGRectGetHeight(group4))];
                [bezier12Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.59110 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.59631 * CGRectGetHeight(group4))];
                [bezier12Path closePath];
                bezier12Path.miterLimit = 4;
                
                [color1 setFill];
                [bezier12Path fill];
                
                
                //// Bezier 14 Drawing
                UIBezierPath* bezier14Path = UIBezierPath.bezierPath;
                [bezier14Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.52025 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50768 * CGRectGetHeight(group4))];
                [bezier14Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.28122 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50768 * CGRectGetHeight(group4))];
                [bezier14Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.22110 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.59631 * CGRectGetHeight(group4))];
                [bezier14Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.54611 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.59631 * CGRectGetHeight(group4))];
                [bezier14Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.52025 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50768 * CGRectGetHeight(group4))];
                [bezier14Path closePath];
                bezier14Path.miterLimit = 4;
                
                [color2 setFill];
                [bezier14Path fill];
            }
            
            
            //// Bezier 16 Drawing
            UIBezierPath* bezier16Path = UIBezierPath.bezierPath;
            [bezier16Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.48894 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47798 * CGRectGetHeight(group4))];
            [bezier16Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.51095 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47798 * CGRectGetHeight(group4))];
            [bezier16Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.50513 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45847 * CGRectGetHeight(group4))];
            [bezier16Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.48894 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47798 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.49985 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.46520 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.49449 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47174 * CGRectGetHeight(group4))];
            [bezier16Path closePath];
            bezier16Path.miterLimit = 4;
            
            [color1 setFill];
            [bezier16Path fill];
            
            
            //// Bezier 18 Drawing
            UIBezierPath* bezier18Path = UIBezierPath.bezierPath;
            [bezier18Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.58502 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4))];
            [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.54333 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4))];
            [bezier18Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.53188 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.42549 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.54047 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.41213 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.53653 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.41837 * CGRectGetHeight(group4))];
            [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.55228 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47808 * CGRectGetHeight(group4))];
            [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.63020 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47808 * CGRectGetHeight(group4))];
            [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.58502 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40745 * CGRectGetHeight(group4))];
            [bezier18Path closePath];
            bezier18Path.miterLimit = 4;
            
            [color2 setFill];
            [bezier18Path fill];
            
            
            //// Bezier 20 Drawing
            UIBezierPath* bezier20Path = UIBezierPath.bezierPath;
            [bezier20Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.57482 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.16727 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.47686 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.55442 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.13664 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.52141 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.11157 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46792 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.47391 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.47096 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.45897 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.46488 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.46201 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10727 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.36101 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.16727 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.41442 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.11157 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.38141 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.13664 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.34303 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.29858 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.33936 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.19976 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.32791 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24970 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.39823 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40481 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.35529 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.33818 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.37685 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.37233 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46783 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.49437 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.41988 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.43779 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.44323 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.46939 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.53743 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.40481 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.49243 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.46939 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.51578 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.43779 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.59262 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.29858 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.55881 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.37223 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.58037 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.33818 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.57482 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.16727 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.60783 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.24970 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.59647 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.19985 * CGRectGetHeight(group4))];
            [bezier20Path closePath];
            [bezier20Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46702 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.36238 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.36790 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25458 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.41227 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.36238 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.36790 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31409 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46702 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.14678 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.36790 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.19507 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.41227 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.14678 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.56614 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25458 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.52177 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.14678 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.56614 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.19507 * CGRectGetHeight(group4))];
            [bezier20Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46702 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.36238 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.56614 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31419 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.52168 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.36238 * CGRectGetHeight(group4))];
            [bezier20Path closePath];
            bezier20Path.miterLimit = 4;
            
            bezier20Path.usesEvenOddFillRule = YES;
            
            [color2 setFill];
            [bezier20Path fill];
        }
        
        
        //// Bezier 22 Drawing
        UIBezierPath* bezier22Path = UIBezierPath.bezierPath;
        [bezier22Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.50971 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51797 * CGRectGetHeight(group4))];
        [bezier22Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46800 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52744 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.50971 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52324 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.49101 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52744 * CGRectGetHeight(group4))];
        [bezier22Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.42630 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51797 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.44500 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52744 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.42630 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.52314 * CGRectGetHeight(group4))];
        [bezier22Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.46800 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50850 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.42630 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51270 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.44500 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50850 * CGRectGetHeight(group4))];
        [bezier22Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.50971 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51797 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.49109 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50850 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.50971 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.51279 * CGRectGetHeight(group4))];
        [bezier22Path closePath];
        bezier22Path.miterLimit = 4;
        
        [color4 setFill];
        [bezier22Path fill];
        
        
        //// Rectangle 4 Drawing
        CGRect rectangle4Rect = CGRectMake(CGRectGetMinX(group4) + floor(CGRectGetWidth(group4) * 0.10765 + 0.5), CGRectGetMinY(group4) + floor(CGRectGetHeight(group4) * 0.57480 + 0.5), floor(CGRectGetWidth(group4) * 0.25648 + 0.5) - floor(CGRectGetWidth(group4) * 0.10765 + 0.5), floor(CGRectGetHeight(group4) * 0.89447 + 0.5) - floor(CGRectGetHeight(group4) * 0.57480 + 0.5));
        NSMutableParagraphStyle* rectangle4Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle4Style.alignment = NSTextAlignmentLeft;
        
        NSDictionary* rectangle4FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Medium" size: textSize], NSForegroundColorAttributeName: color2, NSParagraphStyleAttributeName: rectangle4Style};
        
        [@"H" drawInRect: rectangle4Rect withAttributes: rectangle4FontAttributes];
        
        
        //// Rectangle 6 Drawing
        CGRect rectangle6Rect = CGRectMake(CGRectGetMinX(group4) + floor(CGRectGetWidth(group4) * 0.21745 + 0.2) + 0.3, CGRectGetMinY(group4) + floor(CGRectGetHeight(group4) * 0.57480 + 0.5), floor(CGRectGetWidth(group4) * 0.66021 + 0.2) - floor(CGRectGetWidth(group4) * 0.21745 + 0.2), floor(CGRectGetHeight(group4) * 0.89447 + 0.5) - floor(CGRectGetHeight(group4) * 0.57480 + 0.5));
        NSMutableParagraphStyle* rectangle6Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle6Style.alignment = NSTextAlignmentLeft;
        
        NSDictionary* rectangle6FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Medium" size: textSize], NSForegroundColorAttributeName: color0, NSParagraphStyleAttributeName: rectangle6Style};
        
        [@"app" drawInRect: rectangle6Rect withAttributes: rectangle6FontAttributes];
        
        
        //// Rectangle 8 Drawing
        CGRect rectangle8Rect = CGRectMake(CGRectGetMinX(group4) + floor(CGRectGetWidth(group4) * 0.47505) + 0.5, CGRectGetMinY(group4) + floor(CGRectGetHeight(group4) * 0.57480 + 0.5), floor(CGRectGetWidth(group4) * 0.62389) - floor(CGRectGetWidth(group4) * 0.47505), floor(CGRectGetHeight(group4) * 0.89447 + 0.5) - floor(CGRectGetHeight(group4) * 0.57480 + 0.5));
        NSMutableParagraphStyle* rectangle8Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle8Style.alignment = NSTextAlignmentLeft;
        
        NSDictionary* rectangle8FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Medium" size: textSize], NSForegroundColorAttributeName: color1, NSParagraphStyleAttributeName: rectangle8Style};
        
        [@"S" drawInRect: rectangle8Rect withAttributes: rectangle8FontAttributes];
        
        
        //// Rectangle 10 Drawing
        CGRect rectangle10Rect = CGRectMake(CGRectGetMinX(group4) + floor(CGRectGetWidth(group4) * 0.55724 + 0.2) + 0.3, CGRectGetMinY(group4) + floor(CGRectGetHeight(group4) * 0.57480 + 0.5), floor(CGRectGetWidth(group4) * 1.00000 + 0.2) - floor(CGRectGetWidth(group4) * 0.55724 + 0.2), floor(CGRectGetHeight(group4) * 0.89447 + 0.5) - floor(CGRectGetHeight(group4) * 0.57480 + 0.5));
        NSMutableParagraphStyle* rectangle10Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle10Style.alignment = NSTextAlignmentLeft;
        
        NSDictionary* rectangle10FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Medium" size: textSize], NSForegroundColorAttributeName: color0, NSParagraphStyleAttributeName: rectangle10Style};
        
        [@"nap" drawInRect: rectangle10Rect withAttributes: rectangle10FontAttributes];
    }
}





+ (void)drawBinocularsWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color3 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color4 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color5 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    
    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + 0.37, CGRectGetMinY(frame) + 0.27, CGRectGetWidth(frame) + 0.02, CGRectGetHeight(frame) - 0.52);
    
    
    //// Group
    {
        //// Group 2
        {
            //// Group 3
            {
                //// Group 4
                {
                    //// Bezier 2 Drawing
                    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
                    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.35040 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34184 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21378 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34569 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34184 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21971 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.34184 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15981 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.33327 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34184 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15388 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.33798 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12055 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.11198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15981 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.11584 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.11198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15388 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.11198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21378 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.10342 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.11198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21971 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.10813 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.09697 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.08597 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23490 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.09226 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.08731 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22922 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00244 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58885 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60997 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00110 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.59454 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60404 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77716 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79872 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.78309 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79280 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98921 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00856 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99514 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00385 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.29259 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98921 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.29731 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99514 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85268 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83111 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.84674 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83704 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79872 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77716 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79279 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.78309 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63700 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30972 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62621 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.30116 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63106 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.30501 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62621 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.39174 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62621 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.40031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61543 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.39645 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62621 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.40031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62136 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.40031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23534 * CGRectGetHeight(group))];
                    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.39174 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.40031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22941 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.39645 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.35040 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier2Path closePath];
                    bezier2Path.miterLimit = 4;
                    
                    bezier2Path.usesEvenOddFillRule = YES;
                    
                    [color setFill];
                    [bezier2Path fill];
                }
                
                
                //// Group 5
                {
                    //// Bezier 4 Drawing
                    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
                    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.33224 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.32504 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.33224 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00408 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.32900 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.13200 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.12480 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12804 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12480 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00408 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12480 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.03675 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12480 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04174 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12735 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13612 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05489 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13357 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.13612 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04990 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.13612 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11494 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.14332 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13612 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11993 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.13936 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.31367 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.32087 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11494 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.31763 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.32087 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11993 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.32087 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05489 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.32656 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.32087 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04990 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.32343 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group))];
                    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.33225 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.03675 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.32969 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.33225 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04174 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.33225 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group))];
                    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.33224 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group))];
                    [bezier4Path closePath];
                    bezier4Path.miterLimit = 4;
                    
                    bezier4Path.usesEvenOddFillRule = YES;
                    
                    [color2 setFill];
                    [bezier4Path fill];
                }
            }
            
            
            //// Group 6
            {
                //// Group 7
                {
                    //// Bezier 6 Drawing
                    UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
                    [bezier6Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64959 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.65816 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21378 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65430 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.65816 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21971 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.65816 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15981 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.66672 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65816 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15388 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.66201 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.87945 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.88801 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15981 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.88416 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14902 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.88801 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15388 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.88801 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21378 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.89658 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.88801 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21971 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.89187 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.90302 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.91403 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23490 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.90774 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.91269 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22922 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.99756 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58886 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60997 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99890 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.59454 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60404 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77716 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79873 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.78310 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79280 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98921 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99144 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99515 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99615 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.70743 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98921 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.70272 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99515 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85268 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83112 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.84675 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83704 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79873 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77716 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.79280 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.78309 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63700 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69030 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62622 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69886 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63107 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69501 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62622 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.60828 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62622 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.59972 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61543 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.60357 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62622 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.59972 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62136 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.59972 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23535 * CGRectGetHeight(group))];
                    [bezier6Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.60828 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.59972 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22941 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.60357 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier6Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.64959 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22456 * CGRectGetHeight(group))];
                    [bezier6Path closePath];
                    bezier6Path.miterLimit = 4;
                    
                    bezier6Path.usesEvenOddFillRule = YES;
                    
                    [color3 setFill];
                    [bezier6Path fill];
                }
                
                
                //// Group 8
                {
                    //// Bezier 8 Drawing
                    UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
                    [bezier8Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.66778 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.67499 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.66778 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00408 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.67102 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.86802 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87522 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87522 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00408 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.87522 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.03675 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86955 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87522 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04174 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87267 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86388 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05489 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.86643 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.86388 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04990 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.86388 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11494 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.85668 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.86388 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11993 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.86064 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.68633 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.67913 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11494 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.68237 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12401 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.67913 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11993 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.67913 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05489 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.67345 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.67913 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04990 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.67657 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group))];
                    [bezier8Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.66778 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.03675 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.67034 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04582 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.66778 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.04174 * CGRectGetHeight(group))];
                    [bezier8Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.66778 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00907 * CGRectGetHeight(group))];
                    [bezier8Path closePath];
                    bezier8Path.miterLimit = 4;
                    
                    bezier8Path.usesEvenOddFillRule = YES;
                    
                    [color4 setFill];
                    [bezier8Path fill];
                }
            }
            
            
            //// Group 9
            {
                //// Bezier 10 Drawing
                UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
                [bezier10Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57172 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52985 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55534 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54353 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57172 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54218 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.56435 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54833 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.49999 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53476 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55534 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54353 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.53892 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53476 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44393 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54161 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45398 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53476 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.44393 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54161 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52985 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43532 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54747 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54218 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42905 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38422 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41672 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39656 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28352 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44607 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.42827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27119 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43628 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.48219 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.51779 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.49198 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.50800 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.55393 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28352 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.56372 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26111 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27119 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38422 * CGRectGetHeight(group))];
                [bezier10Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42905 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39656 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41672 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.57173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52985 * CGRectGetHeight(group))];
                [bezier10Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.57172 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52985 * CGRectGetHeight(group))];
                [bezier10Path closePath];
                bezier10Path.miterLimit = 4;
                
                bezier10Path.usesEvenOddFillRule = YES;
                
                [color5 setFill];
                [bezier10Path fill];
            }
        }
    }
}


+ (void) drawMaybeCheckmark
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Rectangle Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 13.54, 12.86);
    CGContextRotateCTM(context, 45 * M_PI / 180);
    
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 15, 5)];
    [color setFill];
    [rectanglePath fill];
    
    CGContextRestoreGState(context);
    
    
    //// Rectangle 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 38.75, 9.79);
    CGContextRotateCTM(context, 135 * M_PI / 180);
    
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 25, 5)];
    [color setFill];
    [rectangle2Path fill];
    
    CGContextRestoreGState(context);
}

+ (void) drawLargeCameraButton : (CGRect) frame
{
    // Drawing code
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Artboard_2
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(51.3, 29.87)];
        [bezier2Path addLineToPoint: CGPointMake(66.11, 29.87)];
        [bezier2Path addCurveToPoint: CGPointMake(68, 31.73) controlPoint1: CGPointMake(67.11, 29.87) controlPoint2: CGPointMake(68, 30.68)];
        [bezier2Path addLineToPoint: CGPointMake(68, 59.73)];
        [bezier2Path addCurveToPoint: CGPointMake(66.11, 61.6) controlPoint1: CGPointMake(68, 60.72) controlPoint2: CGPointMake(67.17, 61.6)];
        [bezier2Path addLineToPoint: CGPointMake(24.89, 61.6)];
        [bezier2Path addCurveToPoint: CGPointMake(23, 59.73) controlPoint1: CGPointMake(23.89, 61.6) controlPoint2: CGPointMake(23, 60.78)];
        [bezier2Path addLineToPoint: CGPointMake(23, 31.73)];
        [bezier2Path addCurveToPoint: CGPointMake(24.89, 29.87) controlPoint1: CGPointMake(23, 30.74) controlPoint2: CGPointMake(23.83, 29.87)];
        [bezier2Path addLineToPoint: CGPointMake(39.7, 29.87)];
        [color0 setStroke];
        bezier2Path.lineWidth = 1.7;
        [bezier2Path stroke];
        
        
        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(57.93, 45.44)];
        [bezier4Path addCurveToPoint: CGPointMake(45.26, 57.92) controlPoint1: CGPointMake(58.05, 52.38) controlPoint2: CGPointMake(52.31, 58.1)];
        [bezier4Path addCurveToPoint: CGPointMake(33.07, 45.91) controlPoint1: CGPointMake(38.63, 57.81) controlPoint2: CGPointMake(33.18, 52.44)];
        [bezier4Path addCurveToPoint: CGPointMake(45.74, 33.42) controlPoint1: CGPointMake(32.89, 38.97) controlPoint2: CGPointMake(38.69, 33.25)];
        [bezier4Path addCurveToPoint: CGPointMake(57.93, 45.44) controlPoint1: CGPointMake(52.37, 33.54) controlPoint2: CGPointMake(57.82, 38.91)];
        [bezier4Path closePath];
        [color0 setStroke];
        bezier4Path.lineWidth = 1.7;
        [bezier4Path stroke];
        
        
        //// Bezier 6 Drawing
        UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
        [bezier6Path moveToPoint: CGPointMake(51.3, 30.33)];
        [bezier6Path addLineToPoint: CGPointMake(51.3, 28.47)];
        [bezier6Path addCurveToPoint: CGPointMake(49.41, 26.6) controlPoint1: CGPointMake(51.3, 27.47) controlPoint2: CGPointMake(50.47, 26.6)];
        [bezier6Path addLineToPoint: CGPointMake(41.53, 26.6)];
        [bezier6Path addCurveToPoint: CGPointMake(39.64, 28.47) controlPoint1: CGPointMake(40.53, 26.6) controlPoint2: CGPointMake(39.64, 27.42)];
        [bezier6Path addLineToPoint: CGPointMake(39.64, 30.33)];
        [color0 setStroke];
        bezier6Path.lineWidth = 1.7;
        [bezier6Path stroke];
        
        
        //// Bezier 8 Drawing
        UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
        [bezier8Path moveToPoint: CGPointMake(64.27, 35.41)];
        [bezier8Path addLineToPoint: CGPointMake(60.78, 35.41)];
        [bezier8Path addCurveToPoint: CGPointMake(58.88, 33.54) controlPoint1: CGPointMake(59.77, 35.41) controlPoint2: CGPointMake(58.88, 34.59)];
        [bezier8Path addLineToPoint: CGPointMake(58.88, 33.54)];
        [bezier8Path addCurveToPoint: CGPointMake(60.78, 31.67) controlPoint1: CGPointMake(58.88, 32.55) controlPoint2: CGPointMake(59.71, 31.67)];
        [bezier8Path addLineToPoint: CGPointMake(64.27, 31.67)];
        [bezier8Path addCurveToPoint: CGPointMake(66.16, 33.54) controlPoint1: CGPointMake(65.28, 31.67) controlPoint2: CGPointMake(66.16, 32.49)];
        [bezier8Path addLineToPoint: CGPointMake(66.16, 33.54)];
        [bezier8Path addCurveToPoint: CGPointMake(64.27, 35.41) controlPoint1: CGPointMake(66.11, 34.53) controlPoint2: CGPointMake(65.28, 35.41)];
        [bezier8Path closePath];
        [color0 setStroke];
        bezier8Path.lineWidth = 1.7;
        [bezier8Path stroke];
        
        
        //// Bezier 10 Drawing
        UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
        [bezier10Path moveToPoint: CGPointMake(39.4, 45.44)];
        [bezier10Path addLineToPoint: CGPointMake(51.07, 45.44)];
        [color0 setStroke];
        bezier10Path.lineWidth = 1.7;
        [bezier10Path stroke];
        
        
        //// Bezier 12 Drawing
        UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
        [bezier12Path moveToPoint: CGPointMake(45.26, 51.39)];
        [bezier12Path addLineToPoint: CGPointMake(45.26, 39.96)];
        [color0 setStroke];
        bezier12Path.lineWidth = 1.7;
        [bezier12Path stroke];
    }
}

+ (void) drawHappSnapIcon : (CGRect) frame
{
    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 0.25 green: 0.25 blue: 0.25 alpha: 0.4];
    UIColor* color1 = [UIColor colorWithRed: 0.259 green: 0.737 blue: 0.384 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.25 green: 0.25 blue: 0.25 alpha: 0.5];
    UIColor* color0 = [UIColor colorWithRed: 0.074 green: 0.601 blue: 0.915 alpha: 1];
    
    
    //// Subframes
    CGRect group2 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.19617 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.61591 + 0.5), floor(CGRectGetWidth(frame) * 0.80813 - 0.4) - floor(CGRectGetWidth(frame) * 0.19617 + 0.5) + 0.9, floor(CGRectGetHeight(frame) * 0.71364) - floor(CGRectGetHeight(frame) * 0.61591 + 0.5) + 0.5);
    CGRect group4 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.28900 + 0.1) + 0.4, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.50591 + 0.1) + 0.4, floor(CGRectGetWidth(frame) * 0.48134 - 0.1) - floor(CGRectGetWidth(frame) * 0.28900 + 0.1) + 0.2, floor(CGRectGetHeight(frame) * 0.58455 - 0.2) - floor(CGRectGetHeight(frame) * 0.50591 + 0.1) + 0.3);
    
    
    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24246 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51776 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61587 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20880 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18110 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51407 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51019 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49526 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49895 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17636 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37151 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24246 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.43901 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18110 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39715 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20862 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34883 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38710 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34422 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27823 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32984 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33328 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41854 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50422 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43076 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46828 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60293 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54051 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47534 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57540 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59447 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50422 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53767 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57540 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.56718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54069 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38710 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62140 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46845 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64869 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43076 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24246 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33328 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66879 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27823 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50522 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45723 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33854 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.43606 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45723 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40411 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50522 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21984 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27297 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43606 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21984 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63043 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33854 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57437 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21984 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63043 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27297 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50522 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45723 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63043 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40411 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57437 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45723 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;
    
    bezier2Path.usesEvenOddFillRule = YES;
    
    [color0 setFill];
    [bezier2Path fill];
    
    
    //// Oval 2 Drawing
    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.45455 - 0.5) + 1, CGRectGetMinY(frame) + floor((CGRectGetHeight(frame) - 5.2) * 0.63082 + 0.2) + 0.3, floor(CGRectGetWidth(frame) * 0.56077 + 0.3) - floor(CGRectGetWidth(frame) * 0.45455 - 0.5) - 0.8, 5.2)];
    [color2 setFill];
    [oval2Path fill];
    
    
    //// Group 2
    {
        //// Bezier 18 Drawing
        UIBezierPath* bezier18Path = UIBezierPath.bezierPath;
        [bezier18Path moveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.76378 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 1.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.88370 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.70232 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier18Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.76378 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier18Path closePath];
        bezier18Path.miterLimit = 4;
        
        [color1 setFill];
        [bezier18Path fill];
        
        
        //// Bezier 20 Drawing
        UIBezierPath* bezier20Path = UIBezierPath.bezierPath;
        [bezier20Path moveToPoint: CGPointMake(CGRectGetMinX(group2) + 0.61735 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier20Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.12413 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier20Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.00000 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier20Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.67068 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 1.00000 * CGRectGetHeight(group2))];
        [bezier20Path addLineToPoint: CGPointMake(CGRectGetMinX(group2) + 0.61735 * CGRectGetWidth(group2), CGRectGetMinY(group2) + 0.00000 * CGRectGetHeight(group2))];
        [bezier20Path closePath];
        bezier20Path.miterLimit = 4;
        
        [color0 setFill];
        [bezier20Path fill];
    }
    
    
    //// Bezier 38 Drawing
    UIBezierPath* bezier38Path = UIBezierPath.bezierPath;
    [bezier38Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65422 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50685 * CGRectGetHeight(frame))];
    [bezier38Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50685 * CGRectGetHeight(frame))];
    [bezier38Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58617 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52438 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59521 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51281 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59060 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51860 * CGRectGetHeight(frame))];
    [bezier38Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58469 * CGRectGetHeight(frame))];
    [bezier38Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71139 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58469 * CGRectGetHeight(frame))];
    [bezier38Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65422 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50685 * CGRectGetHeight(frame))];
    [bezier38Path closePath];
    bezier38Path.miterLimit = 4;
    
    [color0 setFill];
    [bezier38Path fill];
    
    
    //// Group 4
    {
        //// Bezier 40 Drawing
        UIBezierPath* bezier40Path = UIBezierPath.bezierPath;
        [bezier40Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64677 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [bezier40Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.30724 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [bezier40Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [bezier40Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [bezier40Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64677 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.87671 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.70203 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.75832 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.35892 * CGRectGetHeight(group4))];
        [bezier40Path closePath];
        bezier40Path.miterLimit = 4;
        
        [color1 setFill];
        [bezier40Path fill];
    }
    
    
    //// Bezier 42 Drawing
    UIBezierPath* bezier42Path = UIBezierPath.bezierPath;
    [bezier42Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58469 * CGRectGetHeight(frame))];
    [bezier42Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56091 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58469 * CGRectGetHeight(frame))];
    [bezier42Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55353 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56313 * CGRectGetHeight(frame))];
    [bezier42Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58469 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54671 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57049 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53989 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57768 * CGRectGetHeight(frame))];
    [bezier42Path closePath];
    bezier42Path.miterLimit = 4;
    
    [color1 setFill];
    [bezier42Path fill];
    
    
    //// Bezier 44 Drawing
    UIBezierPath* bezier44Path = UIBezierPath.bezierPath;
    [bezier44Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62712 * CGRectGetHeight(frame))];
    [bezier44Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50632 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63606 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63203 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53122 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63606 * CGRectGetHeight(frame))];
    [bezier44Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46114 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62712 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.48143 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63606 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46114 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63203 * CGRectGetHeight(frame))];
    [bezier44Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50632 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61818 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46114 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62221 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.48143 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61818 * CGRectGetHeight(frame))];
    [bezier44Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62712 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53122 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61818 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55150 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62221 * CGRectGetHeight(frame))];
    [bezier44Path closePath];
    bezier44Path.miterLimit = 4;
    
    [color3 setFill];
    [bezier44Path fill];
}



@end
