//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 11/17/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HPStyleKit : NSObject


+ (UIColor *) blueColor;
// Drawing Methods
+ (void)drawAccountIconWithFrame: (CGRect)frame;
+ (void) drawAmbassadorFlagInRect: (CGRect)frame;
+ (void) drawMaybeCheckmark;
+ (void) drawHappSnapIcon : (CGRect) frame;
+ (void) drawLargeCameraButton : (CGRect) frame;
+ (void) drawBinocularsWithFrame: (CGRect)frame;
+ (void)drawTrophyWithFrame: (CGRect)frame;
+ (void)drawHappSnapTitleIconWithFrame: (CGRect)frame;
+ (void)drawWrenchWithRect: (CGRect)rect;
+ (void)drawHeartWithRect: (CGRect)rect;
+ (void)drawTimeWithFrame: (CGRect)frame;
+ (void)drawLocationWithFrame: (CGRect)frame;

@end
