//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 11/17/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HPStyleKit : NSObject

// Drawing Methods
+ (void) drawAmbassadorFlagInRect: (CGRect)frame;

@end
