# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "whatsgoinon" do

pod 'pop', '~> 1.0'
pod 'Parse', '~> 1.2' 
pod 'iCarousel', '~> 1.8'
pod 'Google-Maps-iOS-SDK', '~> 1.8'
pod 'Facebook-iOS-SDK', '~> 3.17'

end

target "whatsgoinonTests" do

end

