# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
source 'https://github.com/CocoaPods/Specs.git'
target "whatsgoinon" do

pod 'pop', '~> 1.0'
pod 'Parse', '~> 1.6.1' 
pod 'iCarousel', '~> 1.8'
pod 'Google-Maps-iOS-SDK', '~> 1.8'
pod 'Facebook-iOS-SDK', '~> 3.17'
pod 'Masonry', '~> 0.5'
pod 'ParseFacebookUtils', '~> 1.2'
pod 'ParseCrashReporting', '~> 1.6'

end

target "whatsgoinonTests" do

end

